### ISSUE TITLE
New-VRAReservation error return

### ISSUE THREAD

**Issue by itayet** [jakkulabs/PowervRA#153]
Hi, I am using PowervRA to create reservations, my script was working until updating the VRA to version 7.2 and my PowerVra Version is 2.2.0 now.
after collecting my data that need to stored in New-VRAReservation parameters i get this error: Invoke-RestMethod : {"errors":[{"code":11001,"message":"The 'reservationStorages' field is required.","systemMessage":"Field with id reservationStorages is required.","moreInfoUrl":null},{"code":11001,"message":"The 'computeResource' field is required.","systemMessage":"Field with id computeResource is required.","moreInfoUrl":null},{"code":11001,"message":"The 'reservationNetworks' field is required.","systemMessage":"Field with id reservationNetworks is required.","moreInfoUrl":null}]} At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PowervRA\2.2.0\Functions\Public\Invoke-vRARestMethod.ps1:128 char:21 + $Response = Invoke-RestMethod @Params + ~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Thanks.

**Comment by jonathanmedd** [comment]
Hi,

We're adding some changes to release v2.2.1 based off some reported issues around New-vRReservation and vRA 7.2 & 7.3 - see issue #149 

With those fixes I have successfully tested creating a Reservation in vRA 7.2 and 7.3. We should have release v2.2.1 out soon. Alternatively, you can get them from the branch 'feature-7.3-support' (soon to be merged to develop - see PR [https://github.com/jakkulabs/PowervRA/pull/154](url)  )

Could you please test again using those fixes? I'm pretty confident that is the issue, since I get the same error if I send through an unknown Resource Type to vRA 7.2, i.e. 'vSphere' rather than the newly required 'vSphere (vCenter)'

**Comment by chelnak** [comment]
Changes are now in the development branch 👍

**Comment by itayet** [comment]
Hi Jonathan,
The fixe below in the New-vRAReservation is working, I am able to create now.
The PowerShell module is very helpful and a useful tool,
Thanks you.

**Comment by jonathanmedd** [comment]
@itayet OK, great - thanks for letting us know and good to hear you find PowervRA useful :-)
