### ISSUE TITLE
Enhancement for cmdlet to export blueprint

### ISSUE THREAD

**Issue by jzajac2** [jakkulabs/PowervRA#160]
Any plans to have a cmdlet for exporting a blueprint? going to try this out: chelnak/Export-Blueprints.ps1

However would be a great addition to PowervRA IMHO.

**Comment by jonathanmedd** [comment]
@jzajac2 The functions in @chelnak 's script you refer to have been renamed in a recent version to drop the word content, since you can put other things in the packages now.

You can find them all here:
https://github.com/jakkulabs/PowervRA/tree/master/src/Functions/Public/content-management-service

So you can still do what's in @chelnak 's script, just change the function names.
