### ISSUE TITLE
Set-vRAEntitlement assumes EntitledCatalogItems

### ISSUE THREAD

**Issue by feardamhan** [jakkulabs/PowervRA#180]
As currently written, when adding a Catalog Item to an Entitlement, Set-vRAEntitlement requires that the Catalog Item already be available to the logged in user via another entitlement. It does this by calling Get-vRAEntitledCatalogItem when attempting to retrieve the catalog item to add. It therefore fails when trying to find a catalog item that is present but which the current user is not entitled to

In this way it behaves differently to when adding a Resource Action which uses Get-vRAResourceOperation to get the Resource Action

Modifying Set-vRAEntitlement to use Get-vRACatalogItem rather than Get-vRAEntitledCatalogItem (and changing flag from EntitledCatalogItems to CatalogItems for clarity) would resolve the issue, and serve both use cases, as would adding an additional parameter such as NonEntitledCatalogItems and having that use Get-vRACatalogItem rather than Get-vRAEntitledCatalogItem

**Comment by jonathanmedd** [comment]
@feardamhan I agree and I've changed my initial reading of this from being an enhancement to a bug. We should use `Get-vRACatalogItem` instead of `Get-vRAEntitledCatalogItem` to make it consistent with how we add Services and Resource Operations.

Also, we are already using `Get-vRACatalogItem` , not `Get-vRAEntitledCatalogItem` to do the same thing in `New-vRAEntitlement`, so should be consistent with that too. 

I'll be updating the code accordingly ASAP to resolve this.

**Comment by feardamhan** [comment]
Sweet. Thanks
