### ISSUE TITLE
Want to be a maintainer of this project?

### ISSUE THREAD

**Issue by jonathanmedd** [jakkulabs/PowervRA#207]
We are seeking up to two additional maintainers for the PowervRA project. The career focus of both project founders @chelnak and @jonathanmedd is no longer on VMware vRA and we appreciate that updates to this project have not been as frequent as they could have been this year. Consequently, we would like to onboard some extra help as maintainers who would be able to contribute both new content that the project needs and also speed up the response to community raised issues and pull requests.

In particular we are keen to develop support for the newly released vRA 8.

If you are interested in being considered, then please reply to this issue with the following information:

- VMware vRA experience
- PowerShell experience
- Open source project experience

It would also be helpful if you would submit some of the below info to help us get a picture of who you are:

Twitter
LinkedIn
Blog (if you have one)

**Comment by peglegzero** [comment]
Hi Jonathan,

don't wish to bug, but we're in prod trying to figure out something that seems rather simple and need some help pls - need a simple script to change the reservation for a vRA-managed VM from X to Y, where both X and Y are currently defined

**Comment by kclinden** [comment]
Are you looking to transfer the project completely or just have another maintainer? I can help either way. 

I work for VMware PSO, and use vRA/vRO every day.

**Comment by jonathanmedd** [comment]
@peglegzero I'd suggest you create a new issue with specific details around what you need. This thread really is for discussion of becoming a maintainer in this project. Thanks

**Comment by jonathanmedd** [comment]
@kclinden Thanks for the interest. We're not looking to transfer the project, just looking for extra help. @chelnak and I are happy to remain in the project, however we don't have the focus to deal with requests (such as the above) in as timely manner as they deserve.

We'll be in touch soon :-)

**Comment by Stevio54** [comment]
Hello,

I am also interested in helping out here. I currently work for kovarus.com as a Sr. Consultant and VMware expert. Just finished my first year as a vExpert, and also have over 15 years experience in software development.

I am very passionate about supplying tools to the community and am working on some of my own projects off and on. 

I was already thinking of forking the repo for here and PowervRO to update for the newest releases since the API was built from the ground up and looks very different. 

My career has also included a lot of managed service like work, which gave me extensive experience with PowerShell as well as many other scripting languages. 

In any case, I wanted to put my hat in the ring and offer my assistance in maintaining this project and helping bring it into the new vRA 8 world. 

This goes for PowervRO as well. 

I have a blog, but due to working on these other ideas I have not done much on it in some time, but have a resolution to change that this year: www.cloudbrackets.com

**Comment by jonathanmedd** [comment]
@Stevio54 Thanks for the interest, sounds good to me. We'll be in touch soon :-)

**Comment by chelnak** [comment]
@Stevio54 Thank you for the interest. I've added you to the Maintainers group. Looking forward to your contribution :-)

**Comment by ymmit85** [comment]
@jonathanmedd I’d be keen to help out also. Use vRA/vRO daily along with PowerShell. Have also been trying to contribute to the PowervROps module (https://GitHub.com/ymmit85/powervrops) which is similar to what you have been doing here.

Twitter: @ymmit85
Blog: ymmit.net

**Comment by jonathanmedd** [comment]
@ymmit85 Thanks for the interest. We've added you to the Maintainers group.

**Comment by jonathanmedd** [comment]
We have enough helpers for now, will re-open if we need further assistance.

**Comment by JohnWarner-Dell** [comment]
I am the team lead for a Dell lab that heavily leverages pretty much the entire VMware suite and am the implementor/maintainer/etc for all things vRealize. As a Powershell kind of guy, I am happy to assist with this project.
